# Generated by Django 2.2.dev20180919211339 on 2018-09-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_user_trova_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='tv enabled')),
                ('trakt_api_key', models.CharField(max_length=254)),
            ],
        ),
    ]
