# Generated by Django 2.1.1 on 2018-10-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20181003_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvconfig',
            name='sonarr_monitored',
            field=models.BooleanField(default=False, verbose_name='Sonarr Show Monitored'),
        ),
        migrations.AlterField(
            model_name='tvconfig',
            name='sonarr_search_missing',
            field=models.BooleanField(default=False, verbose_name='Sonarr Search Missing'),
        ),
    ]
