# Generated by Django 2.1.1 on 2018-10-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_remove_tvconfig_api_key_tvdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvrequest',
            name='sonarr_id',
            field=models.IntegerField(db_index=True, default=1, unique=True),
            preserve_default=False,
        ),
    ]
