# Generated by Django 2.1.1 on 2018-09-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20180927_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvconfig',
            name='suggestions_enabled',
        ),
        migrations.AlterField(
            model_name='tvconfig',
            name='suggestions_anticipated_enabled',
            field=models.BooleanField(default=True, verbose_name='Anticipated Shows'),
        ),
        migrations.AlterField(
            model_name='tvconfig',
            name='suggestions_popular_enabled',
            field=models.BooleanField(default=True, verbose_name='Popular Shows'),
        ),
        migrations.AlterField(
            model_name='tvconfig',
            name='suggestions_trending_enabled',
            field=models.BooleanField(default=True, verbose_name='Trending Shows'),
        ),
    ]
