# Generated by Django 2.2.dev20180919211339 on 2018-10-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_tvrequest_sonarr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvconfig',
            name='sonarr_api_key',
            field=models.CharField(blank=True, max_length=254, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='tvconfig',
            name='sonarr_host',
            field=models.CharField(blank=True, default='localhost', max_length=254, verbose_name='IP or Hostname'),
        ),
        migrations.AlterField(
            model_name='tvconfig',
            name='sonarr_monitored',
            field=models.BooleanField(default=False, verbose_name='Show Monitored'),
        ),
        migrations.AlterField(
            model_name='tvconfig',
            name='sonarr_port',
            field=models.IntegerField(blank=True, default='8989', null=True, verbose_name='Port'),
        ),
        migrations.AlterField(
            model_name='tvconfig',
            name='sonarr_quality_profile',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quality Profile'),
        ),
        migrations.AlterField(
            model_name='tvconfig',
            name='sonarr_search_missing',
            field=models.BooleanField(default=False, verbose_name='Search Missing'),
        ),
        migrations.AlterField(
            model_name='tvconfig',
            name='sonarr_season_folders',
            field=models.BooleanField(default=False, verbose_name='Season Folders'),
        ),
        migrations.AlterField(
            model_name='tvconfig',
            name='sonarr_ssl',
            field=models.BooleanField(default=False, verbose_name='SSL Enabled'),
        ),
        migrations.AlterField(
            model_name='tvconfig',
            name='sonarr_sub_directory',
            field=models.CharField(blank=True, max_length=254, verbose_name='URL Path'),
        ),
        migrations.AlterField(
            model_name='tvconfig',
            name='sonarr_tv_dir',
            field=models.CharField(blank=True, max_length=254, verbose_name='TV Media Root'),
        ),
    ]
