# Generated by Django 2.1.1 on 2018-09-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20180927_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvconfig',
            name='sonarr_enabled',
            field=models.BooleanField(default=False, verbose_name='Sonarr Enabled'),
        ),
        migrations.AddField(
            model_name='tvconfig',
            name='sonarr_quality_profile',
            field=models.IntegerField(blank=True, default=1, verbose_name='Sonarr Quality Profile'),
        ),
        migrations.AddField(
            model_name='tvconfig',
            name='sonarr_season_folders',
            field=models.BooleanField(default=False, verbose_name='Sonarr Season Folders'),
        ),
        migrations.AddField(
            model_name='tvconfig',
            name='sonarr_ssl',
            field=models.BooleanField(default=False, verbose_name='Sonarr SSL Enabled'),
        ),
        migrations.AddField(
            model_name='tvconfig',
            name='sonarr_sub_directory',
            field=models.CharField(blank=True, default='localhost', max_length=254, verbose_name='Sonarr Sub-directory'),
        ),
        migrations.AddField(
            model_name='tvconfig',
            name='sonarr_tv_dir',
            field=models.CharField(blank=True, max_length=254, verbose_name='Sonarr TV Directory'),
        ),
        migrations.AddField(
            model_name='tvconfig',
            name='sonnar_api_key',
            field=models.CharField(blank=True, max_length=254, verbose_name='Sonarr API Key'),
        ),
        migrations.AddField(
            model_name='tvconfig',
            name='sonnar_host',
            field=models.CharField(blank=True, default='localhost', max_length=254, verbose_name='Sonarr IP or Hostname'),
        ),
        migrations.AddField(
            model_name='tvconfig',
            name='sonnar_port',
            field=models.IntegerField(blank=True, default=8989, verbose_name='Sonarr Port'),
        ),
    ]
