# Generated by Django 2.1.1 on 2018-09-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_auto_20180928_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvconfig',
            name='require_approval',
            field=models.BooleanField(default=True, verbose_name='TV Approval Required'),
        ),
    ]
