# Generated by Django 2.1.1 on 2018-10-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_auto_20181003_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvrequest',
            name='name',
            field=models.CharField(blank=True, max_length=254, verbose_name='Show Name'),
        ),
    ]
