# Generated by Django 2.1.1 on 2018-09-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_tvconfig_require_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvconfig',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='tvconfig',
            name='require_approval',
            field=models.BooleanField(default=True, verbose_name='Approval Required'),
        ),
    ]
