# Generated by Django 2.1.1 on 2018-10-04 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_tvrequest_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvrequest',
            old_name='name',
            new_name='title',
        ),
    ]
