# Generated by Django 2.1.1 on 2018-09-28 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_auto_20180928_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvconfig',
            name='sonarr_enabled',
        ),
    ]
