# Generated by Django 2.1.1 on 2018-10-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_auto_20181004_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvconfig',
            name='sonarr_timezone',
            field=models.CharField(blank=True, max_length=254, verbose_name='Timezone Sonarr is Hosted'),
        ),
    ]
