# Generated by Django 2.1.1 on 2018-09-28 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_remove_tvconfig_sonarr_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvconfig',
            name='require_approval',
        ),
    ]
