# Generated by Django 2.1.1 on 2018-10-08 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_tvconfig_sonarr_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvrequest',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, max_length=254, verbose_name='Requested Date'),
            preserve_default=False,
        ),
    ]
