# Generated by Django 2.1.1 on 2018-09-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_remove_tvconfig_require_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvconfig',
            name='sonarr_quality_profile',
            field=models.IntegerField(blank=True, verbose_name='Sonarr Quality Profile'),
        ),
        migrations.AlterField(
            model_name='tvconfig',
            name='sonarr_season_folders',
            field=models.BooleanField(verbose_name='Sonarr Season Folders'),
        ),
        migrations.AlterField(
            model_name='tvconfig',
            name='sonarr_ssl',
            field=models.BooleanField(verbose_name='Sonarr SSL Enabled'),
        ),
        migrations.AlterField(
            model_name='tvconfig',
            name='sonarr_sub_directory',
            field=models.CharField(blank=True, max_length=254, verbose_name='Sonarr URL Path'),
        ),
        migrations.AlterField(
            model_name='tvconfig',
            name='sonarr_tv_dir',
            field=models.CharField(blank=True, max_length=254, verbose_name='Sonarr TV Folder Root'),
        ),
        migrations.AlterField(
            model_name='tvconfig',
            name='sonnar_host',
            field=models.CharField(blank=True, max_length=254, verbose_name='Sonarr IP or Hostname'),
        ),
        migrations.AlterField(
            model_name='tvconfig',
            name='sonnar_port',
            field=models.IntegerField(blank=True, verbose_name='Sonarr Port'),
        ),
    ]
