# Generated by Django 2.1.1 on 2018-10-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_tvrequest_request_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='trova_admin',
            new_name='admin',
        ),
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.BooleanField(default=False),
        ),
    ]
