# Generated by Django 2.1.1 on 2018-09-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_auto_20180928_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvconfig',
            name='sonarr_quality_profile',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sonarr Quality Profile'),
        ),
        migrations.AlterField(
            model_name='tvconfig',
            name='sonnar_port',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sonarr Port'),
        ),
    ]
