# Generated by Django 2.1.1 on 2018-09-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_auto_20180928_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvconfig',
            old_name='enabled',
            new_name='tv_enabled',
        ),
        migrations.AlterField(
            model_name='tvconfig',
            name='sonarr_season_folders',
            field=models.BooleanField(default=False, verbose_name='Sonarr Season Folders'),
        ),
        migrations.AlterField(
            model_name='tvconfig',
            name='sonarr_ssl',
            field=models.BooleanField(default=False, verbose_name='Sonarr SSL Enabled'),
        ),
        migrations.AlterField(
            model_name='tvconfig',
            name='sonnar_host',
            field=models.CharField(blank=True, default='localhost', max_length=254, verbose_name='Sonarr IP or Hostname'),
        ),
        migrations.AlterField(
            model_name='tvconfig',
            name='sonnar_port',
            field=models.IntegerField(blank=True, default='8989', null=True, verbose_name='Sonarr Port'),
        ),
    ]
