# Generated by Django 2.1.1 on 2018-09-28 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_auto_20180928_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvconfig',
            old_name='sonnar_api_key',
            new_name='sonarr_api_key',
        ),
        migrations.RenameField(
            model_name='tvconfig',
            old_name='sonnar_host',
            new_name='sonarr_host',
        ),
        migrations.RenameField(
            model_name='tvconfig',
            old_name='sonnar_port',
            new_name='sonarr_port',
        ),
    ]
